global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['nodejs:3000']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo:27017']
