global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:27017']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

mountPoints = [{
  containerPath = "/etc/prometheus/"
  sourceVolume  = "prometheus_config"
}]
